apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expense-tracker
  template:
    metadata:
      labels:
        app: expense-tracker
    spec:
      containers:
      - name: expense-tracker
        image: stardust96/expense-tracker:d896ad552b8b7b9e10818b642852545b4ba20f02
        imagePullPolicy: Always
        ports:
        - containerPort: 80
