apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expense-tracker
  template:
    metadata:
      labels:
        app: expense-tracker
    spec:
      containers:
      - name: expense-tracker
        image: stardust96/expense-tracker:fbfda4a0f9c20ea6bc05c707ac3e73e5ebdf6919
        imagePullPolicy: Always
        ports:
        - containerPort: 80
